#+TITLE: BQN's Quantum Noise
#+INCLUDE: "../html-head.org"

** Preamble

We will implement and test a SchrГ¶dinger-style[fn:1] quantum simulator in the BQN[fn:2] programming language.
Initially, we import the necessary system functions and define a 1-modifier for handling
complex-valued matrix products. Next, we define a namespace containing various quantum gates:

#+name: preamble
#+begin_src bqn :exports code :tangle ../bqn/q.bqn
  SinвҖҝCosвҖҝGCD вҶҗ вҖўmath
  U вҶҗ вҖўrand.Range
  _cp вҶҗ {(-Вҙрқ”ҪВЁ)вӢҲ(+Вҙрқ”ҪВЁ)вҹңвҢҪ}
    
  g вҶҗ {
    IM вҶҗ (вҠўвӢҲвүўвҘҠвҹң0вҠў)ВЁ
    xвҖҝidвҖҝh вҮҗ (вҢҪвҖҝвҠў{рқ•Һрқ•©}ВЁ<=вҢңЛңвҶ•2) вҲҫв—ӢIM <-вҢҫ(1вҖҝ1вҠёвҠ‘)2вҖҝ2вҘҠГ·вҲҡ2
    swapвҖҝcnot вҮҗ IM вҹЁ1вҖҝ2, 2вҖҝ3вҹ© {вҢҪвҢҫ(рқ•ЁвҠёвҠҸ)рқ•©}ВЁ <=вҢңЛңвҶ•4
    P вҮҗ {вҹЁ=вҢңЛңвҶ•4,  4вҖҝ4вҘҠ0вҹ© {рқ•ЁвҢҫ(3вҖҝ3вҠёвҠ‘)рқ•©}ВЁЛң SinвҠёвӢҲвҹңCosрқ•©}
  }
#+end_src

** Interpreter

The (call_count-chars() chars[fn:3]) quantum interpreter is based on references [[https://arxiv.org/abs/1711.02086][arXiv:1711.02086]]
and [[https://arxiv.org/abs/1608.03355][arXiv:1608.03355]]. For simplicity, we always measure at the end of the execution:

#+name: interpreter
#+begin_src bqn :exports code :tangle ../bqn/q.bqn
  Q вҶҗ {рқ•ҠqbвҖҝscвҖҝr:
    wf вҶҗ (1вҢҫвҠ‘вӢҲвҠў)вҘҠвҹң0 2вӢҶqb
    M вҶҗ +ЛқвҲҳГ—вҺү1вҖҝвҲһ _cp
    K вҶҗ {1рқ•Ҡрқ•©:рқ•©; рқ•Ёрқ•Ҡ1:рқ•Ё; рқ•ЁвҲҫвҲҳГ—вҹң<_cpрқ•©}
    L вҶҗ {рқ•©KвҚҹрқ•Ё1}{KВҙвҹЁg.idрқ”ҪЛңqb-рқ•Ё+вҢҠ2вӢҶвҒјвү вҠ‘рқ•©, рқ•©, рқ•Ёрқ”Ҫg.idвҹ©}
    T вҶҗ вҲҫвҶ•вҲҳвү {(вҠўвҲҫ1вҶ“вҢҪ)рқ•ЁвҶ“вҶ•рқ•ЁвҠ‘вҹңрқ•©ЛңвҖў_while_>рқ•ЁвҠ‘рқ•©}ВЁ<
    A вҶҗ {1=вү вҠ‘рқ•Ё ? рқ•©MЛңвҠ‘вҠёLВҙрқ•Ё; ui вҶҗ 0вҠёLВҙрқ•Ё
      рқ•©MЛңГ—вҲҳвү в—¶uiвҖҝ(MЛңВҙMвҹңuiвҹңMЛңMВҙ) Lвҹңg.swapВЁT рқ•Ё(вҢҪвҲҳвҠўвҲҫВ¬вҲҳвҲҠ/вҠЈ)вҹңвҠ‘ЛңвҶ•qb
    }
    В»вҠё<вҲЁ` 0>r-`>+в—Ӣ(Г—Лң)Лқ wf AВҙвҢҪsc
  }
#+end_src

#+begin_export html
</br>
<details>
<summary>Physical context</summary>
#+end_export

The interpreterвҖҷs logic is straightforward: it evolves the wavefunction $\Psi_0^n$  
in the full [[https://en.wikipedia.org/wiki/Hilbert_space][Hilbert space]], whose dimension is $2^n$ for $n$ qubits.  
Each quantum gate is extended to this space through Kronecker lifting,  
performed by the function =L=:

\begin{equation*}
  L_U = I \otimes \cdots U \cdots \otimes I
\end{equation*}

Note that the function =L= performs more than a plain Kronecker embedding.  
Before constructing \(L_U\), the affected qubits are permuted to become  
index-adjacent in the tensor order. This permutation is decomposed into  
adjacent swaps, applied as unitary transpositions (=T=). The system then evolves
under the sequence of lifted gates, defined by =A=:

\begin{equation*}
\Psi_m^n = \Psi_0^n \prod_i^m L_{U_i}
\end{equation*}

Measurement is implemented by sampling from the [[https://en.wikipedia.org/wiki/Cumulative_distribution_function][CDF]] of the squared amplitudes of the state vector.  
Statistically, this corresponds to drawing a discrete random variable $q_j$ whose  
cumulative distribution is:

\begin{equation*}
  F(q_j) = \sum_{i \le j}p(q_i)
\end{equation*}

Given a uniform random variable $U \sim \text{Uniform}(0, 1)$, we sample by inversion:

\begin{equation*}
  \text{Pr}(U \in (F(q_{j-1}), F(q_{j})]) = \text{Pr}(F(q_{j-1}) < U \le F(q_{j})) = F(q_{j}) - F(q_{j-1}) = p(q_{j})
\end{equation*}

#+begin_export html
</details>
#+end_export

** Shor's algorithm

As a test case, we employ the quantum circuit of Shor's algorithm
for the number fifteen and base eleven, following references
[[https://arxiv.org/abs/1804.03719][arXiv:1804.03719]] and [[https://arxiv.org/abs/2306.09122][arXiv:2306.09122]]. The resulting compiled circuit
uses five qubits, three of which serve as control. To enhance
statistical accuracy, the experiment is repeated multiple times.

#+name: test
#+begin_src bqn :exports code :results none :tangle ../bqn/q.bqn
  nвҖҝaвҖҝqbвҖҝr вҶҗ вҹЁ15, 11, 5, 0 UЛң 2вӢҶ3вҹ©

  sc вҶҗ вҹЁ
    вҹЁ0вҹ©вҖҝg.h вӢ„ вҹЁ1вҹ©вҖҝg.h вӢ„ вҹЁ2вҹ©вҖҝg.h
    вҹЁ2, 3вҹ©вҖҝg.cnot вӢ„ вҹЁ2, 4вҹ©вҖҝg.cnot вӢ„ вҹЁ1вҹ©вҖҝg.h
    вҹЁвҹЁ1, 0вҹ©, g.P ПҖГ·2вҹ© вӢ„ вҹЁ0вҹ©вҖҝg.h
    вҹЁвҹЁ1, 2вҹ©, g.P ПҖГ·4вҹ© вӢ„ вҹЁвҹЁ0, 2вҹ©, g.P ПҖГ·2вҹ© вӢ„ вҹЁ2вҹ©вҖҝg.h
  вҹ©

  C вҶҗ {n (вҠЈвүЎГ—ВҙвҲҳGCD) +вҖҝ-{рқ•©рқ•Һ1}ВЁ <aвӢҶ(вү Г·2Г—вҠ‘вҲҳвҚ’) 0вҢҫвҠ‘+ЛқвҲҳвҖҝ(2вӢҶqb-2)вҘҠрқ•©}
#+end_src

The function =C= performs the classical post-processing part of the algorithm.
Given the measurement registers, it reconstructs the candidate period \(r\) and
checks the Shor certificate: it is true iff both \(\gcd(a^{\,r/2}\pm 1,N)\)
are non-trivial and their product equals \(N\).

LetвҖҷs run the quantum simulation and complete the reasoning in the classical domain;
let us kill the ignorabimus. Wir mГјssen wissen, wir werden wissen![fn:4]

#+name: run
#+begin_src bqn :exports both :tangle ../bqn/q.bqn
  C >+Лқ{Q qbвҖҝscвҖҝрқ•©}ВЁ r
#+end_src

#+RESULTS: run
: 1

Compare the result with that obtained using an IBM's [[https://panadestein.github.io/blog/supp/ibm_eagle/shor_factorize_fifteen.html][Eagle QPU]].

** Epilogue

This was, of course, a conceptually simple simulation, the minimal instance of  
ShorвҖҷs algorithm that has been verified experimentally. The interpreter itself  
remains in its basic, non-optimized form. Yet for me, the goal was different:  
to stress-test BQN on a genuinely technical task. I enjoyed distilling the  
essence of a long and intricate implementation into a few concise expressions,  
like trimming a bonsai.

In that process, the language revealed its character.  
Why the hieroglyphs, you may ask? The tacit and functional style woven from  
combinators, turns programming into a quiet algebraic game.  
The resulting program feels less written than discovered, its complexity  
compressed into a handful of primitives. BQN is the epitome of minimalism's  
power, and the primitive statistics below tell the same story in numbers:

#+begin_export html
<details>
<summary>Primitive's stats</summary>
#+end_export

The src_bqn[:exports code]{prog} string contains the full source code. We used:

#+begin_src bqn :noweb yes :noweb-prefix no :exports none :tangle no :results none
  prog вҶҗ "<<preamble>><<interpreter>><<test>><<run>>"
#+end_src

#+begin_src bqn :noweb yes :noweb-prefix no :exports both :tangle no :wrap example
  prog (+ВҙвҠёвүҚвҹңвү вҲҠ)Лң вҠ‘ВЁвҖўprimitives
#+end_src

#+RESULTS:
#+begin_example
вҹЁ 44 64 вҹ©
#+end_example

With this distribution:

#+begin_src bqn :noweb yes :noweb-prefix no :exports both :tangle no :wrap example
  вҚү>(вҚ·вҲҫвү )ВЁвҲҳ(вҠҗвҠёвҠ”вҲҠ/вҠЈ)вҹң(вҠ‘ВЁвҖўprimitives)Лң prog
#+end_src

#+RESULTS:
#+begin_example
в”Ңв”Җ                                                                                                                                                                                 
в•ө '-' 'Вҙ' 'ВЁ' 'вӢҲ' '+' 'вҹң' 'вҢҪ' 'вҠў' 'вүў' 'вҘҠ' '<' '=' 'вҢң' 'Лң' 'вҶ•' 'вҲҫ' 'в—Ӣ' 'вҢҫ' 'вҠё' 'вҠ‘' 'Г·' 'вҲҡ' 'вҠҸ' 'вҠЈ' 'вӢҶ' 'Лқ' 'вҲҳ' 'Г—' 'вҺү' 'вҚҹ' 'вҢҠ' 'вҒј' 'вү ' 'вҶ“' '>' 'в—¶' 'В¬' 'вҲҠ' '/' 'В»' 'вҲЁ' '`' 'вүЎ' 'вҚ’'  
  6   9   10  4   7   10  6   6   1   5   7   4   3   13  6   5   2   5   7   11  5   1   1   3   5   4   9   6   1   1   1   1   5   2   4   1   1   1   1   1   1   2   1   1    
                                                                                                                                                                                  в”ҳ
#+end_example

#+begin_export html
</details>
#+end_export

BQN is also fast:


#+begin_export html
<details>
<summary>Benchmarks</summary>
#+end_export

While the interpreter's performance is not particularly optimized, here is a comparison with the equivalent Common Lisp code:

#+begin_src bash :exports results :tangle no :results raw :wrap example
  hyperfine --runs 5 'cbqn -f ../bqn/q.bqn' 'sbcl --script ../../supp/perf_qi/q.lisp'
#+end_src

#+RESULTS:
#+begin_example
Benchmark 1: cbqn -f ../bqn/q.bqn
  Time (mean Вұ Пғ):      27.6 ms Вұ   1.1 ms    [User: 26.3 ms, System: 1.1 ms]
  Range (min вҖҰ max):    26.5 ms вҖҰ  29.1 ms    5 runs
 
Benchmark 2: sbcl --script ../../supp/perf_qi/q.lisp
  Time (mean Вұ Пғ):     36.288 s Вұ  0.411 s    [User: 36.427 s, System: 0.231 s]
  Range (min вҖҰ max):   35.709 s вҖҰ 36.701 s    5 runs
 
Summary
  cbqn -f ../bqn/q.bqn ran
 1316.34 Вұ 55.49 times faster than sbcl --script ../../supp/perf_qi/q.lisp
#+end_example

And here is a full program's profile. All time is spent in the Kronecker and matrix products:

#+begin_src bqn :exports both :tangle no :results raw :wrap example
  )profile C >+Лқ{Q qbвҖҝscвҖҝрқ•©}ВЁ r
#+end_src

#+RESULTS:
#+begin_example
Got 125 samples
(REPL): 125 samples:
      в”ӮQ вҶҗ {рқ•ҠqbвҖҝscвҖҝr:
      в”Ӯ  wf вҶҗ (1вҢҫвҠ‘вӢҲвҠў)вҘҠвҹң0 2вӢҶqb
      в”Ӯ  M вҶҗ +ЛқвҲҳГ—вҺү1вҖҝвҲһ _cp
    30в”Ӯ  K вҶҗ {1рқ•Ҡрқ•©:рқ•©; рқ•Ёрқ•Ҡ1:рқ•Ё; рқ•ЁвҲҫвҲҳГ—вҹң<_cpрқ•©}
     1в”Ӯ  L вҶҗ {рқ•©KвҚҹрқ•Ё1}{KВҙвҹЁg.idрқ”ҪЛңqb-рқ•Ё+вҢҠ2вӢҶвҒјвү вҠ‘рқ•©, рқ•©, рқ•Ёрқ”Ҫg.idвҹ©}
      в”Ӯ  T вҶҗ вҲҫвҶ•вҲҳвү {(вҠўвҲҫ1вҶ“вҢҪ)рқ•ЁвҶ“вҶ•рқ•ЁвҠ‘вҹңрқ•©ЛңвҖў_while_>рқ•ЁвҠ‘рқ•©}ВЁ<
     2в”Ӯ  A вҶҗ {1=вү вҠ‘рқ•Ё ? рқ•©MЛңвҠ‘вҠёLВҙрқ•Ё; ui вҶҗ 0вҠёLВҙрқ•Ё
    92в”Ӯ    рқ•©MЛңГ—вҲҳвү в—¶uiвҖҝ(MЛңВҙMвҹңuiвҹңMЛңMВҙ) Lвҹңg.swapВЁT рқ•Ё(вҢҪвҲҳвҠўвҲҫВ¬вҲҳвҲҠ/вҠЈ)вҹңвҠ‘ЛңвҶ•qb
      в”Ӯ  }
      в”Ӯ  В»вҠё<вҲЁ` 0>r-`>+в—Ӣ(Г—Лң)Лқ wf AВҙвҢҪsc
      в”Ӯ}
#+end_example

#+begin_export html
</details>
#+end_export

Try running the simulation in the call_generate-bqn-link() and explore it!
If you are an Emacs user, the =org-mode= computational notebook in
the blog's [[https://github.com/Panadestein/blog][repository]] provides the best experience.

#+name: generate-bqn-link
#+begin_src emacs-lisp :noweb yes :noweb-prefix no :exports none :results raw :tangle no
  (let* ((bqn-code (concat "<<preamble>>\n\n" "<<interpreter>>\n\n" "<<test>>\n\n" "<<run>>"))
         (encoded (base64-encode-string (encode-coding-string bqn-code 'utf-8) t)))
    (concat "[[https://mlochbaum.github.io/BQN/try.html#code=" encoded "][BQN repl]]"))
#+end_src

#+name: count-chars
#+begin_src emacs-lisp :noweb yes :noweb-prefix no :exports none :results raw :tangle no
  (- (length "<<interpreter>>") 4)
#+end_src

[fn:1] Although conceptually straightforward, a Hilbert space of size =2вӢҶn= makes this type of simulation a true computational challenge.
For an efficient implementation, see [[https://arxiv.org/abs/1710.05867v4][arXiv:1710.05867]].
[fn:2] This post's title is a playful recursive acronym that employs quantum computing terminology, without any specific significance
beyond that.
[fn:3] I optimized it up to this number, but I wasn't targeting the Kolmogorov complexity.
[fn:4] Hilbert's [[https://mathweb.ucsd.edu/~williams/motiv/hilbert.html][radio address]] in 1930.

#+INCLUDE: "../html-foot.org"
