#+TITLE: A coding impromptu 
#+INCLUDE: "../html-head.org"
#+HTML_HEAD: <style>
#+HTML_HEAD:   #table-of-contents > h2 { display: none; } /* Hide the default TOC heading */
#+HTML_HEAD:   #table-of-contents > ul { display: block; } /* Ensure TOC content is shown */
#+HTML_HEAD: </style>

This post is a rolling collection of algorithms and computational ideas I like, implemented in BQN.
The current selection includes:

#+TOC: headlines 2 :ignore-title t

The categories above are more hints than strict taxonomies. Occasionally, an entry here grows enough to deserve
its own dedicated post, leaving behind only a link or a memory. Extrapolating Perlis' remark[fn:1], it's likely
that a group of 50 individuals would devise 35 to 40 distinct solutions to even the simplest problem in BQN.
Therefore, I will sometimes juxtapose my implementations with those of seasoned /BQNators/[fn:2].

** Competitive programming

Problems I find in coding challenges' platforms, such as [[https://leetcode.com/u/panadestein/][LeetCode]], [[https://cses.fi/problemset/][CSES]], [[https://cp-algorithms.com/][cp-algorithms]], and [[https://adventofcode.com/][Advent of Code]].

*** Trapping rain water

This is a classical interview [[https://leetcode.com/problems/trapping-rain-water/][problem]] that can be solved in linear time. Interestingly,
it admits a very elegant array solution:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  (+ВҙвҠў-ЛңвҢҲ`вҢҫвҢҪвҢҠвҢҲ`) [0,1,0,2,1,0,1,3,2,1,2,1]
#+end_src

#+RESULTS:
: 6

That is, we take the minimum of max-scans from the left and from the right, and subtract the corresponding height.
Reducing the resulting array gives the amount of trapped water.

A closely related problem is [[https://leetcode.com/problems/container-with-most-water/][container with most water]], which unfortunately is not so easy to solve in linear
time using an array approach (one can easily implement the imperative two pointers solution in BQN, but it
will probably be slow). Here are two solutions, one \(O(n^2)\) and the other \(O(n\log n)\), both tacit:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  вҹЁвҢҲВҙвҲҳвҘҠвҢҠвҢңЛңГ—В·-вҢңЛңвҠ’Лң, вҢҲВҙвҲЁГ—(вҢҲ`вҠё-вҢҲвҠў-вҢҠ`)вҲҳвҚ’вҹ© {10 рқ•ҺвҖў_timedрқ•©}ВЁ< вҖўrand.RangeЛң1e4
#+end_src

#+RESULTS:
: вҹЁ 0.080050875 4.14558eВҜ5 вҹ©

*** Z algorithm

This is a very efficient procedure that finds prefix strings in [[https://cp-algorithms.com/string/z-function.html][linear time]]. The imperative
implementation reads:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  ZI вҶҗ {рқ•Ҡs:
    lвҖҝrвҖҝz вҶҗ 0вҡҮ0 0вҖҝ0вҖҝs
    z вҠЈ {
      v вҶҗ r(вҠў1вҠё+вҖў_while_{(рқ•©+рқ•Ё)<вү s ? =ВҙвҹЁрқ•©,рқ•©+рқ•Ёвҹ©вҠ‘ВЁ<s ; 0}<в—¶({zвҠ‘Лңрқ•©-l}вҢҠ-+1)вҖҝ0)рқ•©
      r <в—¶@вҖҝ{рқ•Ҡ: lвҶ©рқ•©-v+1 вӢ„ rвҶ©рқ•©} рқ•©+v-1
      z vвҢҫ(рқ•©вҠёвҠ‘)вҶ©
    }ВЁ вҶ•вү s
  }
  ZI "abacabadabacaba"
#+end_src

#+RESULTS:
: вҹЁ 15 0 1 0 3 0 1 0 7 0 1 0 3 0 1 вҹ©

Two algorithmic improvements can be made here, namely only iterate
over indices where the character found is equal to the first character, and only search
to extend the count if it goes up to the end of r:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  ZFun вҶҗ {рқ•Ҡs:
    CountEq вҶҗ { 1вҠё+вҖў_while_((вү рқ•Ё)вҠёвүӨв—¶вҹЁвҠ‘вҹңрқ•ЁвүЎвҠ‘вҹңрқ•©,0вҹ©) 0 }
    lвҶҗrвҶҗ0 вӢ„ Ulr вҶҗ {(rвҢҲвҶ©рқ•Ё+рқ•©)>r ? lвҶ©рқ•Ё вӢ„ рқ•©; рқ•©}
    SearchEq вҶҗ вҠЈ Ulr вҠў + + CountEqв—Ӣ(вҶ“вҹңs) вҠў
    Set вҶҗ {iрқ•Ҡрқ•©: ((r-i) (i SearchEq 0вҢҲвҠЈ)вҚҹвүӨ (i-l)вҠ‘рқ•©)вҢҫ(iвҠёвҠ‘) рқ•© }
    (вҢҪ1вҶ“/вҠ‘вҠё=s) SetВҙЛң вҶ‘Лңвү s
  }
#+end_src

I came up with two array versions, with quadratic and cubic time complexities respectively:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  ZAQ вҶҗ ВҜ1вҶ“вҶ“(+ВҙВ·вҲ§`вҠЈ=вү вҠёвҶ‘)ВЁ<
  ZAC вҶҗ (+ВҙвҲ§`)ВЁ<=вҶ•вҲҳвү {В«вҚҹрқ•Ёрқ•©}вҢң<
  (ZAQвүЎZAC)в—¶@вҖҝZAC "abacabadabacaba"
#+end_src

#+RESULTS:
: вҹЁ 15 0 1 0 3 0 1 0 7 0 1 0 3 0 1 вҹ©

With further refinements, the earlier solutions can be transformed into:

#+begin_src bqn :tangle ../bqn/rollim.bqn
  ZAQвҖҝZAC вҶҗ {(+ВҙвҲ§`)ВЁрқ•Ҹ}ВЁ вҹЁвү вҶ‘вҶ“=вҢҪвҲҳвҶ‘, <=В«вҚҹ(вҶ•вҲҳвү )вҹ©
#+end_src

*** Longest increasing sub-sequence

This [[https://en.wikipedia.org/wiki/Longest_increasing_subsequence][problem]] can be solved in \(O(n\log n)\) using dynamic programming. Here is an
imperative implementation which is quadratic, but can be optimized:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  LISI вҶҗ {
    kвҖҝdp вҶҗ ВҜ1вҖҝ(вҲһВЁрқ•©)
    {i вҶҗ вҲ§Вҙв—¶(вҠ‘вҠҗвҹң0)вҖҝ{рқ•Ҡ:k+вҶ©1} dp<рқ•© вӢ„ dp рқ•©вҢҫ(iвҠёвҠ‘)вҶ©}ВЁ рқ•©
    +ВҙвҲһ>dp
  }
  LISIВЁ вҹЁ0вҖҝ1вҖҝ0вҖҝ3вҖҝ2вҖҝ3, 10вҖҝ9вҖҝ2вҖҝ5вҖҝ3вҖҝ7вҖҝ101вҖҝ18, 7вҖҝ7вҖҝ7вҖҝ7вҖҝ7вҹ©
#+end_src

#+RESULTS:
: вҹЁ 4 4 1 вҹ©

A more elegant array solution is:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  LISA вҶҗ +ВҙвҲһвү вҲһВЁ{рқ•ЁвҢҫ((вҠ‘рқ•©вҚӢрқ•Ё-1)вҠёвҠ‘)рқ•©}ВҙвҢҪ
  LISAВЁ вҹЁ0вҖҝ1вҖҝ0вҖҝ3вҖҝ2вҖҝ3, 10вҖҝ9вҖҝ2вҖҝ5вҖҝ3вҖҝ7вҖҝ101вҖҝ18, 7вҖҝ7вҖҝ7вҖҝ7вҖҝ7вҹ©
#+end_src

#+RESULTS:
: вҹЁ 4 4 1 вҹ©

Let's =)explain= this optimized version, so we can truly appreciate its beauty:

#+begin_src bqn :exports results
  )explain +ВҙвҲһвү вҲһВЁ{рқ•ЁвҢҫ((вҠ‘рқ•©вҚӢрқ•Ё-1)вҠёвҠ‘)рқ•©}ВҙвҢҪ
#+end_src

#+RESULTS:
#+begin_example
 +ВҙвҲһвү вҲһВЁ{рқ•ЁвҢҫ((вҠ‘рқ•©вҚӢрқ•Ё-1)вҠёвҠ‘)рқ•©}ВҙвҢҪ 
 в”Ӯ в”Ӯ в”Ӯ в”Ӯв”Ӯ    в”Ӯ в”Ӯ в”Ӯ  в”Ӯ в”Ӯ  в”Ӯ 
 в”Ӯ в”Ӯ в”Ӯ {в”јв”Җв”Җв”Җв”Җв”јв”Җв”јв”Җв”јв”Җв”Җв”јв”Җв”јв”ҖВҙв”Ӯ 
 в”Ӯ в”Ӯ вҲһВЁ в”Ӯ    в”Ӯ в”Ӯ в”Ӯ  в”Ӯ в”Ӯ в”Ӯв”Ӯ 
 в”Ӯ в”Ӯ  в””в”Җв”јв”Җв”Җв”Җв”Җв”јв”Җв”јв”Җв”јв”Җв”Җв”јв”Җв”јв”Җв”јвҢҪ 
 в”Ӯ вҲһвү в”Җв”Җв”Җв”јв”Җв”Җв”Җв”Җв”јв”Җв”јв”Җв”јв”Җв”Җв”јв”Җв”јв”Җв”ҳ  
 +Вҙ в”Ӯ   в”Ӯ    в”Ӯ в”Ӯ в”Ӯ  в”Ӯ в”Ӯ    
  в””в”Җв”ҳ   в”Ӯ    в”Ӯ в”Ӯ в”Ӯ  в”Ӯ в”Ӯ    
        в”Ӯ    в”Ӯ рқ•Ё-1  в”Ӯ в”Ӯ    
        в”Ӯ    рқ•©вҚӢв”Җв”ҳ   в”Ӯ в”Ӯ    
        в”Ӯ   вҠ‘в”Җв”ҳ     в”Ӯ в”Ӯ    
        в”Ӯ   в””в”Җв”Җв”Җв”Җв”Җв”ҖвҠёвҠ‘ в”Ӯ    
        рқ•ЁвҢҫв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ  в”Ӯ    
         в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җрқ•©    
в•¶в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
#+end_example

The full expression is structured as a two-train: we sum all finite entries from the
result of the rightmost three-train. The three-train is a right fold over the reversed
input, with an initial array of =вҲһ= and the same length as the input. In each step
of the fold, we modify the right argument using under: we perform a binary search
with strict comparison to find where the next element should go.
The element is either placed at the end of the unfilled region, or it replaces
the first element that is greater than =рқ•Ё=. Since BQN uses a based array model,
we pick the enclosed atom from this operation's result. So it goes[fn:3].

*** N-queens problem

This problem is the archetypal example of backtracking. Initially, I tried to solve it
using a function to place the queens in the full board, hoping that it would lead to a
more array oriented solution:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  8 {((вҲЁвҢңВҙ0вҠё=)вҲЁ(0=-вҢңВҙ)вҲЁ0=+вҢңВҙ) рқ•©-ВЁ<вҶ•рқ•Ё} 2вҖҝ3
#+end_src

#+RESULTS:
#+begin_example
в”Ңв”Җ                 
в•ө 0 1 0 1 0 1 0 0  
  0 0 1 1 1 0 0 0  
  1 1 1 1 1 1 1 1  
  0 0 1 1 1 0 0 0  
  0 1 0 1 0 1 0 0  
  1 0 0 1 0 0 1 0  
  0 0 0 1 0 0 0 1  
  0 0 0 1 0 0 0 0  
                  в”ҳ
#+end_example

This resulted in a more complicated algorithm, so I decided to go for the classical
Wirth implementation:

#+begin_src bqn :tangle ../bqn/rollim.bqn :results none
  NQ вҶҗ {рқ•Ҡn:
    VвҖҝP вҶҗ {вҠЈрқ•Ҹ(вҠўвҲҫ-вӢҲ+)ВҙвҲҳвҠў}ВЁ вҹЁвҲЁВҙвҠ‘ВЁЛң, {1вҢҫ(рқ•©вҠёвҠ‘)рқ•Ё}ВЁвҹ©
    {nвү рқ•© ? +Вҙ(рқ•ЁVвҠў)в—¶вҹЁ(рқ•©+1)рқ•ҠЛңрқ•ЁPвҠў,0вҹ©вҲҳ(рқ•©вӢҲвҠў)ВЁ вҶ•n ; 1
    }ЛңВҙ (0вӢҲ0Г—В·вҶ•ВЁвҠўвҲҫВ·вӢҲЛң+Лң)n 
  }
#+end_src

Which nicely compares with the OEIS [[https://oeis.org/A000170][sequence]]:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  a000170 вҶҗ 1вҖҝ0вҖҝ0вҖҝ2вҖҝ10вҖҝ4вҖҝ40вҖҝ92
  a000170 вүЎ NQВЁ 1+вҶ•8
#+end_src

#+RESULTS:
: 1

And of course, in the implementation above I could have used a single array instead of three,
but I find the resulting validation and position functions very aesthetic the way they are.

*** Majority element

The [[https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_majority_vote_algorithm][BoyerвҖ“Moore]] algorithm allows for finding the majority element (element that appears
more than =вҢҠрқ•©Г·2= times in the array) in linear time. If such element exists, then it is
equal to the mode of the data, and for this task we have a nice array [[https://mlochbaum.github.io/bqncrate/?q=mode#][solution]]. The original
implementation could be expressed as:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  BM вҶҗ {vвҶҗ0 вӢ„ IвҶҗвҠўвҠЈ=в—¶{рқ•Ҡ:v+вҶ©1}вҖҝ{рқ•Ҡ:v-вҶ©1} вӢ„ 0{рқ•Ҡ:v=0}в—¶вҹЁI,IЛңвҠЈвҹ©Вҙрқ•©}
  BM 6вҖҝ1вҖҝ3вҖҝ1вҖҝ3вҖҝ3вҖҝ4вҖҝ3вҖҝ3вҖҝ5
#+end_src

#+RESULTS:
: 3

The previous fold tracks the majority element as state, a more elegant approach maintains
the number of votes:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  BM вҶҗ {eвҶҗ@ вӢ„ 0{рқ•©=0 ? eвҶ©рқ•ЁвӢ„1 ; рқ•©+ВҜ1вӢҶeвүўрқ•Ё}Вҙрқ•© вӢ„ e}
  BM 6вҖҝ1вҖҝ3вҖҝ1вҖҝ3вҖҝ3вҖҝ4вҖҝ3вҖҝ3вҖҝ5
#+end_src

#+RESULTS:
: 3


*** H-index

This metric is one of the reasons for the [[https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2407748][deplorable]] state of modern academia,
and the headaches for /outsiders/ trying to get in. Consider that Peter Higgs
has an estimated h-index of only [[https://www.semanticscholar.org/author/P.-W.-Higgs/50750305][12]]. By contrast, a random professor nowadays 
boasts an h-index ten times as high, and exponentially less impact.
Enough of ranting, let's concentrate on finding an elegant way to
implement this useless thing:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  HL вҶҗ (+ВҙвҲҳВ«вҠ’ЛңвүӨ+`вҢҫвҢҪ)В·/вҒјвү вҠёвҢҠ
  HS вҶҗ +ВҙвҲЁвүҘ1+вҠ’Лң
  (HLвүЎHS)в—¶@вҖҝHL 14вҖҝ14вҖҝ11вҖҝ9вҖҝ5вҖҝ5вҖҝ1вҖҝ1вҖҝ1вҖҝ1вҖҝ0
#+end_src

#+RESULTS:
: 5

If someone ever published that much, sorting will eventually be slower:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  HLвҖҝHS {рқ•ҺвҖў_timedрқ•©}ВЁ< 1e8 вҖўrand.Range 1e3
#+end_src

#+RESULTS:
: вҹЁ 0.083824959 0.21801262700000001 вҹ©

A testament to the idea that the simplest solution in BQN is often the most efficient:
I initially clip my citations array with ={вү ВЁвҠ”вү вҲҳрқ•©ВЁвҢҫ(вүҘвҹңвү вҲҳрқ•©вҠё/)рқ•©}=, which is just =/вҒјвү вҠёвҢҠ=.

*** Array style breath-first search

If your problem is small enough to fit comfortably within a dense adjacency matrix,
you won't find a more elegant BFS algorithm than the one presented
in this excellent GraphBLAS [[https://archive.fosdem.org/2020/schedule/event/graphblas/][talk]].

#+begin_src bqn :tangle ../bqn/rollim.bqn
  BFS вҶҗ {1+ВҙВ¬вҲЁ`рқ•©вҲЁЛқвҲҳвҲ§вҚҹnрқ•Ё=nвҶҗвҶ•вү рқ•©}
#+end_src

#+RESULTS:
: (function block)


** Numerical methods

I love numerical analysis. Compact implementations are often helpful to get the big picture.

*** Solving the cubic equation

This function computes the real roots of an arbitrary [[https://en.wikipedia.org/wiki/Cubic_equation][cubic equation]]. Initially,
the equation is transformed into its depressed form via an appropriate substitution.
Depending on the sign of the discriminant, the roots are then determined using Cardano's
method when the discriminant is positive, or ViГЁteвҖҷs trigonometric method when it is negative.
In the case where the discriminant is zero, the proportionality to the square
of the Vandermonde polynomial implies that a repeated root is present, the roots
are resolved through direct analytical methods. We have chosen those methods to avoid
using complex numbers, which are not yet supported in BQN.

#+begin_src bqn :tangle ../bqn/rollim.bqn
  Cub вҶҗ {aвҖҝbвҖҝcвҖҝd:
    (bГ·3Г—a)-ЛңвҖўmath{
      рқ•©>0 ? +Вҙрқ•©(рқ•—.Cbrt+вӢҲ-)вҹңвҲҡЛң-qГ·2;
      рқ•©=0 ? 0вҠё=в—¶вҹЁВҜ1вҖҝ2вҖҝ2Г·ЛңВ·рқ•—.CbrtГ—вҹң4,3вҠёвҘҠвҹ©q;
      (2Г—вҲҡ-pГ·3)Г—рқ•—.Cos(2Г—ПҖГ—вҶ•вҠёГ·3)-Лң3Г·Лңрқ•—.Acos(вҲҡ-3Г·p)Г—1.5Г—qГ·p
    }(27Г·ЛңpвӢҶ3)+4Г·ЛңГ—ЛңqвҶҗ(dГ·a)-(27Г·Лң3вӢҶЛңbГ·a)+3Г·ЛңbГ—aГ·ЛңpвҶҗ(cГ·a)-3Г·ЛңГ—ЛңbГ·a
  }
#+end_src

#+RESULTS:
: (function block)

The above implementation only works for the case where =aвүў0=, it will yield =NaN= otherwise.
Here are some tests for the four possible branches:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  CubВЁ вҹЁ1вҖҝ0вҖҝВҜ7вҖҝ6, 1вҖҝВҜ1вҖҝВҜ8вҖҝ12, 1вҖҝВҜ6вҖҝ12вҖҝВҜ8, 1вҖҝ3вҖҝ0вҖҝВҜ1вҹ© 
#+end_src

#+RESULTS:
: вҹЁ вҹЁ 2.0000000000000004 1 ВҜ3.0000000000000004 вҹ© вҹЁ ВҜ2.9999999999999996 1.9999999999999998 1.9999999999999998 вҹ© вҹЁ 2 2 2 вҹ© вҹЁ 0.532088886237956 ВҜ0.6527036446661387 ВҜ2.879385241571817 вҹ© вҹ©

*** QR decomposition

I put some effort golfing this [[https://en.wikipedia.org/wiki/QR_decomposition][QR decomposition]] implementation, and I got a very satisfying
98 chars [[https://codegolf.stackexchange.com/a/278570/94421][one-liner]]. Ungolfed a bit, it looks like this:

#+begin_src bqn :tangle ../bqn/rollim.bqn
  QR вҶҗ +ЛқвҲҳГ—вҺү1вҖҝвҲһ{
    1=вҠўВҙвүўрқ•© ? рқ•©вҠёГ·вҹңвҠ‘вҠёвӢҲ+ЛқвҢҫ(Г—Лң)рқ•©;
    вҲҫЛҳ{(qрқ”Ҫрқ•Ё)вӢҲ(rрқ”Ҫt)вҲҫ0рқ”ҪвҚҹkрқ•©}Вҙрқ•Ҡрқ”Ҫ{рқ•ҳ-рқ•©рқ”ҪtвҶ©рқ•©вҚүвҠёрқ”Ҫрқ•ҳ}(kвҶ“Лҳрқ•©)вҠ‘qвҖҝrвҶҗрқ•Ҡрқ•©вҶ‘ЛҳЛңkвҶҗвҢҲ2Г·ЛңвҠўВҙвүўрқ•©вҠЈtвҶҗ@
  }
#+end_src

#+RESULTS:
: +ЛқвҲҳГ—вҺүвҹЁ 1 вҲһ вҹ©(1-modifier block)

The function works like this: it recursively computes the QR decomposition of a matrix by first
handling the base case (normalizing a single column) then splitting the matrix into two halves.
The first half is decomposed into \(Q_0\) and \(R_0\), and the second half is orthogonalized
against \(Q_0\) by subtracting its projection, yielding a residual matrix that is itself
decomposed into \(Q_1\) and \(R_1\). Finally, the overall orthogonal matrix \(Q\) is formed
by horizontally concatenating \(Q_0\) and \(Q_1\), and the upper triangular \(R\) is assembled
as a block matrix combining \(R_0\), the projection coefficients, and \(R_1\):

\begin{equation*}
  Q \, R = \begin{pmatrix} Q_0 & Q_1 \end{pmatrix} \begin{pmatrix} R_0 & T \\ 0 & R_1 \end{pmatrix} = Q_0 R_0 + Q_0 T + Q_1 R_1,
\end{equation*}

We can test it with random matrices:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  (вҠўвҲҫвҹң<m-+ЛқвҲҳГ—вҺү1вҖҝвҲһВҙ) QR m вҶҗ 3вҖҝ3вҖўrand.Range 0
#+end_src

#+RESULTS:
: в”Ңв”Җ                                                                                                                                             
: В· в”Ңв”Җ                                                               в”Ңв”Җ                                                               в”Ңв”Җ         
:   в•ө 0.7144260899509619  ВҜ0.11998405924866697 ВҜ0.6893469282760241   в•ө 1.3272602613914946 0.45821006669986125  0.6778483350121149     в•ө 0 0 0    
:     0.24775066978035085  0.9647413811697029   0.0888463453506213     0                  0.697172106504235   ВҜ0.13992817528755036      0 0 0    
:     0.6543813625255287  ВҜ0.23426031030668987  0.7189625438047855     0                  0                    0.029863470562463006     0 0 0    
:                                                                  в”ҳ                                                                в”ҳ         в”ҳ  
:                                                                                                                                               в”ҳ

*** Fast Fourier Transform

Below is an implementation of the radix-2 [[https://en.wikipedia.org/wiki/Cooley%E2%80%93Tukey_FFT_algorithm][CooleyвҖ“Tukey FFT algorithm]]. The function leverages
BQN's headers to define the inverse transform in a succinct way using the property:

\begin{equation*}
  \text{iFFT}[\mathbf{x}] = \frac{1}{N}\text{FFT}^{*}[\mathbf{x}^{*}]
\end{equation*}

We also define a namespace for dealing with complex numbers, in particular the =Cis= function:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports code
  z вҶҗ {
    _p вҮҗ {(-Вҙрқ”ҪВЁ)вӢҲ(+Вҙрқ”ҪВЁ)вҹңвҢҪ}
    CвҖҝE вҮҗ вҹЁвӢҲвҹң-ВҙЛҳ, вҖўmath{рқ•—.CosвүҚЛҳрқ•—.Sin}вҹ©
  }
  FFT вҶҗ {рқ•ҠвҒј: z.C{вү Г·ЛңВ·рқ”Ҫрқ”ҫвҲҳрқ”Ҫ}рқ•Ҡрқ•©; (1=вү )в—¶вҹЁ(+вҲҫ-)вҹң(вҠўГ—z._pЛҳВ·z.EвҲҳ-ПҖГ—вҶ•вҠёГ·вҲҳвү )Вҙ(рқ•ҠВЁвҠўвҠ”Лң2|вҠ’Лң), вҠўвҹ©рқ•©}
#+end_src

#+RESULTS:
: (function block)

Let's confirm that the inverse returns back the original list:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  (+ВҙвҲҳвҘҠвҠў-FFTвҒјвҲҳFFT) 0вҖўrand.RangeЛң2вӢҲЛң2вӢҶ10
#+end_src

#+RESULTS:
: 1.914614300435602eВҜ14

We could also compare with the discrete Fourier transform, which despite being \(O(N^2)\)
+has+ should have a nice array formulation:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  DFT вҶҗ вүҚЛҳВҙ<Лҳ{рқ”ҪвҲҳвҚү+ЛқвҲҳГ—вҺү1вҖҝвҲһ z._pЛңВ·рқ”Ҫ1вҖҝ0вҚүвҒјВ·z.E ВҜ2Г—ПҖГ—вү Г·ЛңВ·Г—вҢңЛңвҠ’Лң}
  (+ВҙвҲҳвҘҠFFT-DFT) 0вҖўrand.RangeЛң2вӢҲЛң2вӢҶ10
#+end_src

#+RESULTS:
: ВҜ2.8412011632283907eВҜ10

In the DFT code above, I got into a big mess with the complex numbers, because the
=z= namespace was too tightly coupled with the FFT implementation. I had to do a
bunch of enclosing and coupling to get the same shape. With proper complex numbers
support it would be something like:

#+begin_src bqn :tangle ../bqn/rollim.bqn
  DFT вҶҗ вҠў+ЛқвҲҳГ—вҺү1вҖҝвҲһЛңВ·вӢҶВҜ2Г—ПҖГ—вү Г·ЛңВ·Г—вҢңЛңвҠ’Лң
#+end_src

*** Tensor n-mode product

The n-mode product is a key ingredient for computing the Tucker decomposition of a tensor.
For this we can use the [[https://en.wikipedia.org/wiki/Higher-order_singular_value_decomposition][HOSVD]] algorithm: a method that has been rediscovered several times.
For example, in the nuclear quantum dynamics community it is known as =POTFIT= and
was published before the often cited De Lathauwer paper, see [[https://arxiv.org/abs/1309.5060][arXiv:1309.5060]] for a discussion.
For a tensor \(\mathcal{X}\) and a matrix \(U\) we define:

\begin{equation*}
  (\mathcal{X} \times_n U)_{i_1,\dots,i_{n-1},\,j,\,i_{n+1},\dots,i_N} = \sum_{i_n=1}^{I_n} x_{i_1,\dots,i_n,\dots,i_N}\, u_{j,i_n}.
\end{equation*}

In BQN's parlance, we can express it as:

#+begin_src bqn :tangle ../bqn/rollim.bqn
  {+ЛқвҲҳГ—вҺү1вҖҝвҲһвҹңрқ•©вҢҫ(вҚүвҚҹрқ•—)рқ•Ё}
#+end_src

A beautiful example of notation as a tool of thought, in my opinion: this deferred 1-modifier
(itself a compact melange of six modifiers) computes the рқ•—-mode product of a tensor рқ•Ё and a matrix рқ•©.
It works by moving the рқ•—-axis to the front, then multiplying рқ•Ё and рқ•© without the need for explicit
unfolding, courtesy of the rank operator, and moving the last axis of the result back to рқ•—, all
gracefully managed by under.

*** k-means clustering

A classic algorithm in machine learning for unsupervised clustering.
I was once asked to recognize it in an interview, but I didnвҖҷt know it at the time.
Pity, its implementation is deceptively simple:

#+begin_src bqn :tangle ../bqn/rollim.bqn
  KMC вҶҗ {
    _fp вҶҗ {рқ•ҠвҲҳвҠўвҚҹвүўвҹңрқ”Ҫрқ•©}
    c вҶҗ рқ•Ё(вҖўrand.Dealвҹңвү вҠҸвҠў)рқ•©
    рқ•©вҠё(>В·(+ЛқГ·вү )ВЁвҠЈвҠ”ЛңВ·вҠҸвҲҳвҚӢЛҳ(+ВҙГ—Лң)вҲҳ-вҺү1вҺү1вҖҝвҲһ)_fp c
  }
#+end_src

#+RESULTS:
: (function block)

Here I have chosen to implement the algorithm as a fixed point, but I am not filtering empty groups.
You can fix that by adding a =вҖў_while_= instead, with an appropriate stopping condition.
To obtain the labels, simply record the result of =вҠҸвҲҳвҚӢЛҳ= (or =вҠҗвҹң(вҢҠВҙ)=, which is faster).
Bellow is a test with some sample data:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  test вҶҗ [
    0вҖҝ0, 0вҖҝ1, 1вҖҝ0
    5вҖҝ0, 5вҖҝ1, 6вҖҝ0
    0вҖҝ5, 1вҖҝ5, 0вҖҝ6
    5вҖҝ5, 5вҖҝ6, 6вҖҝ5
  ]
  3 KMC test
#+end_src

#+RESULTS:
: в”Ңв”Җ                                       
: в•ө 5.333333333333333  2.8333333333333335  
:   0.3333333333333333 0.3333333333333333  
:   0.3333333333333333 5.333333333333333   
:                                         в”ҳ

Keep in mind that LloydвҖҷs algorithm can converge to local minima, and that apparently distinct
solutions may in fact be equivalent up to permutation or geometric symmetry (rotations, reflections, etc.).

*Update*: check out the [[https://mlochbaum.github.io/bqncrate/?q=k-me][BQNcrate version]] that was added after some discussion in the Matrix room.

*** Solving linear systems

[[https://en.wikipedia.org/wiki/Gaussian_elimination][Gaussian elimination]] is one of the first techniques one learns in any numerical analysis course.
The implementation below is the classical \(O(\frac{2}{3}N^3)\) with partial pivoting. It relies
on outer products to eliminate columns below the pivot in a more vectorized fashion:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports code
  GE вҶҗ {
    mвҖҝv вҶҗ ВҜ1(вҶ“ЛҳвӢҲВ·вҘҠвҶ‘Лҳ)рқ•©{
      p вҶҗ рқ•Ё+вҠ‘вҠҗвҹң(вҢҲВҙ)|рқ•ЁвҶ“рқ•ЁвҠҸЛҳрқ•©
      рқ•ЁвҠёвҠҸ{(вҠў-В·0ВЁвҢҫвҠҸрқ”ҪЛҳГ—вҢңвҠҸ)Г·вҹңрқ”ҪвҢҫвҠҸ}вҢҫ(рқ•ЁвҠёвҶ“)вҚҹ(0вү рқ•ЁвҖҝрқ•ЁвҠёвҠ‘)вҢҪвҢҫ(рқ•ЁвҖҝpвҠёвҠҸ)рқ•©
    }ВҙвҢҪвҶ•вҢҠВҙрқ•©вүўвҠё-вҶ•2
    (0ВЁ{(vрқ•ЁвҠёвҠ‘вҠё-вҠ‘рқ•©+ЛқвҲҳГ—вҺү1вҖҝвҲһв—Ӣ(рқ•ЁвҠёвҶ“)рқ•ЁвҠҸm)вҢҫ(рқ•ЁвҠёвҠ‘)рқ•©}ВҙвҠ’Лң)v
  }
#+end_src

The second pass (back substitution) is a purely functional fold that resolves the variable vector =v=
by threading the known solutions upwards against the upper-triangular matrix =m=. A bit janky for my taste.
The implementation of Gauss-Jordan, which is \(O(N^3)\), does deliver the elegance I seek:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports code
  GJ вҶҗ {
    вҠўВҙЛҳрқ•©{
      p вҶҗ рқ•Ё+вҠ‘вҠҗвҹң(вҢҲВҙ)|рқ•ЁвҶ“рқ•ЁвҠҸЛҳрқ•©
      рқ•ЁвҠёвҠҸ{(вҠў-В·0ВЁвҢҫрқ”Ҫрқ”ҪЛҳГ—вҢңрқ”Ҫ)Г·вҹңрқ”ҪвҢҫрқ”Ҫ}вҚҹ(0вү рқ•ЁвҖҝрқ•ЁвҠёвҠ‘)вҢҪвҢҫ(рқ•ЁвҖҝpвҠёвҠҸ)рқ•©
    }ВҙвҢҪвҶ•вҢҠВҙрқ•©вүўвҠё-вҶ•2
  }
#+end_src

We can confirm the correctness of both implementations by solving a random system and checking the
resulting residual. If they are equal up to a tolerance, we compare the CPU times. Regardless of the
theoretical time complexity, Gauss-Jordan is faster in BQN due to its vectorized nature:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  {1eВҜ10>|+Вҙ(GE-GJ)рқ•©}в—¶@вҖҝ(GEвҖў_timedГ·GJвҖў_timed) (вҠўвҖўrand.RangeЛңвҠўвӢҲ+вҹң1) 1e3
#+end_src

#+RESULTS:
: 19.52462177736598

*** Chebyshev coefficients of the first kind

There is a compact expression already in the [[https://mlochbaum.github.io/bqncrate/?q=cheb#][BQNcrate]], which efficiently implements the
standard recurrence:

\begin{equation*}
  T_n(x) = 2x T_{n-1}(x) - T_{n-2}(x)
\end{equation*}

I wanted to explore an alternative approach that I haven't seen so often. Instead of viewing $T_n$
as the child of $T_{n-1}$, we view it as the solution to an eigenvalue problem. The polynomial $T_n(x)$
is the eigenfunction of the [[https://en.wikipedia.org/wiki/Chebyshev_equation][Chebyshev Differential Equation]] with eigenvalue $n^2$:

\begin{equation*}
  (1-x^2)y'' - xy' + n^2y = 0
\end{equation*}

Using the Frobenius method, we assume a solution of the form $y = \sum a_k x^k$. Plugging this
into the ODE gives us a direct relationship between coefficients of power $k$ and $k+2$:

\begin{equation*}
  a_{k+2} (k+2)(k+1) + a_k (n^2 - k^2) = 0
\end{equation*}

Now we only need an suitable initial condition. Fortunately, for all Chebyshev polynomials (odd or even),
the leading coefficient is determined by the normalization $T_n(x) \approx (2x)^n \dots$, so $a_n = 2^{n-1}$.
By starting at the singularity ($k=n$) and flowing down to $k=0$, we avoid all parity checks and singularities:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports code
  T вҶҗ {
    v вҶҗ Г—`(1вҢҲ2вӢҶрқ•©-1)вҢҫвҠ‘Г·ЛқвҹЁ1,рқ•©,2,-рқ•©вҹ©+вҢңp вҶҗ рқ•©-2Г—вҶ•1+вҢҠрқ•©Г·2
    vвҢҫ(pвҠёвҠҸ)0вҘҠЛңрқ•©+1
  }
#+end_src

#+RESULTS:
: (function block)

Using some beautiful array tricks, like folding division over a list of functions, which nicely
simplifies fractions of binomials due to the "inverted" operation order of =Г·=; and creating
an alternate boolean mask by scanning =вү =, which eliminates the need for the clunky under, Marshall
transformed the previous function into this (little-endian):

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports code
  T вҶҗ {вҢҪ(вҠўГ—Г—`вҲҳвӢҶ)вҹң(вү `1ВЁ)(1вҢҲ2вӢҶрқ•©-1)вҲҫГ·ЛқвҹЁ1,рқ•©,2,-рқ•©вҹ©+вҢңвҢҪвҶ•рқ•©}
#+end_src

#+RESULTS:
: (function block)

And here is the typical table:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  {
    A вҶҗ "x"вҲҫ"вҒ°В№ВІВівҒҙвҒөвҒ¶вҒ·вҒёвҒ№"вҠҸЛң'0'-ЛңвҖўFmt
    B вҶҗ вҠў/ЛңВ·В¬вү вҶ‘"1x"вҚ·вҠў
    C вҶҗ 1вҶ“В·вҲҫвҲҳвҢҪ0вҠёвү /Г—вҠёвҠҸвҹң" +-"вҲҫВЁвҖўFmtвҲҳ|ВЁвҲҫВЁВ·AВЁвҠ’Лң
    (>вҠўвҶ‘ВЁЛңВ·вҢҲВҙвү ВЁ)(B CвҲҳTвҶ“ЛңВҜ2+2вҠё|)ВЁвҶ•рқ•©
  } 11
#+end_src

#+RESULTS:
#+begin_example
в”Ңв”Җ                                   
в•ө"1                                  
  x                                  
  2xВІ-1                              
  4xВі-3x                             
  8xвҒҙ-8xВІ+1                          
  16xвҒө-20xВі+5x                       
  32xвҒ¶-48xвҒҙ+18xВІ-1                   
  64xвҒ·-112xвҒө+56xВі-7x                 
  128xвҒё-256xвҒ¶+160xвҒҙ-32xВІ+1           
  256xвҒ№-576xвҒ·+432xвҒө-120xВі+9x         
  512xВ№вҒ°-1280xвҒё+1120xвҒ¶-400xвҒҙ+50xВІ-1" 
                                    в”ҳ
#+end_example


** Array programming

Here are some tricks and I ideas I find useful in array programming, many of them born from some REPL exploration.

*** An identity on the naturals

Some time ago, while working on performance optimization of linear algebra
operations with Boolean arrays, I encountered an
interesting summation property for an array \(a\) of length \(n\):

\begin{equation*}
    \sum_{i | a_i \neq 0} \sum_{j=i+1} f_j
  = \sum_{j=0} f_j \sum_{i < j | a_i \neq 0} 1
\end{equation*}

It turns out that the RHS can be elegantly transformed
into a scan, giving rise to a beautiful identity that applies to all
natural numbers, not just Booleans as I initially thought:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  (+`вүЎВ·+Вҙ/вүӨвҹң<вҠ’Лң) вҖўrand.RangeЛң 1e3
#+end_src

#+RESULTS:
: 1

This identity holds because =вҠ’Лң= represents the indices =i= of the list,
and since =+Вҙ(/рқ•©)=i вҶҗвҶ’ iвҠ‘рқ•©=, the fold sums all the elements in =рқ•©= up to =i=, for
=i= in the range of the length of the list. Ergo, a scan.

*** Depth of nested lists

Studying tree algorithms in APL, I learned about the depth vector [[https://asherbhs.github.io/apl-site/trees/representing-trees.html][representation]]. If
the nested object in consideration is a string, the best approach is using boolean [[https://mlochbaum.github.io/bqncrate/?q=depth%20of%20parens#][masks]].
However, when dealing with a BQN list, recursion becomes necessary to determine
the depth of nested elements. HereвҖҷs how it can be implemented:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  {=в—¶вҹЁвӢҲ0, 1+В·вҲҫрқ•ҠВЁвҹ©рқ•©} вҹЁ1, вҹЁ2, вҹЁ3вҹ©, вҹЁ4, вҹЁ5, вҹЁ6, 7вҹ©вҹ©вҹ©вҹ©, 1вҹ©
#+end_src

#+RESULTS:
: вҹЁ 1 2 3 3 4 5 5 1 вҹ©

*** Another fun spiral

There are many variants of the spiral matrix problem. One fun version appears in the 
[[https://cses.fi/problemset/task/1071][CSES]] problem set, which I attempted to generate using array programming techniques. 
In particular, I implemented a variation of Joey TuttleвҖҷs remarkable method 
for constructing integer volutes. For background, see this [[https://tony-zorman.com/posts/volutes-in-bqn.html][post]], which also links to
the original APL and J sources.

#+begin_src bqn :tangle ../bqn/rollim.bqn
  Z1 вҶҗ {вҲҳвҖҝрқ•©вҘҠвҚӢ+`(вҘҠ1вҲҫЛҳвүҚЛҳЛңвҶ•рқ•©)(вҠЈ/В·-вҢҫ(2вҠҸЛҳвҲҳвҖҝ3вҠёвҘҠ)вү вҠёвҘҠ)рқ•©вҖҝ1}
#+end_src

#+RESULTS:
: (function block)

The key to TuttleвҖҷs method is understanding the role of grade up as a permutation inverter.
Rather than constructing the spiral directly, the algorithm first generates a =value вҶ’ position= map.
This list is created by a scan that integrates a sequence of delta moves capturing the spiral's path =P=,
that is, a simulation of the process with =вҹЁ1, рқ•©, ВҜ1, -рқ•©вҹ©= corresponding to steps right, down, left, up.
The resulting path vector is a map where =kвҠ‘P= is the final flattened position for the value =k=.
The grade up =вҚӢP= then inverts this relationship, transforming it into a =position вҶ’ value=
map: the final flattened spiral.

Interestingly, this particular problem also has a concise closed-form solution, 
described beautifully in this other [[https://susam.net/zigzag-number-spiral.html][post]], made zero based with the observation that
=рқ•ЁвҢҲв—Ӣ(1вҠё+)рқ•©= is =1+рқ•ЁвҢҲрқ•©=:

#+begin_src bqn :tangle ../bqn/rollim.bqn
  Z2 вҶҗ (Г—ЛңвҠё+вҲҳвҢҲ--Г—ВҜ1вӢҶвҢҲ)вҢңЛңвҶ•
#+end_src

#+RESULTS:
: (Г—ЛңвҠё-вҲҳвҢҲ+-Г—ВҜ1вӢҶвҢҲ)вҢңЛң1+вҶ•

LetвҖҷs confirm that both methods produce identical results:

#+begin_src bqn :tangle ../bqn/rollim.bqn :exports both
  (Z1вүЎZ2)в—¶@вҖҝZ1 вҠ‘1 вҖўrand.Deal 10
#+end_src

#+RESULTS:
: в”Ңв”Җ                
: в•ө  0  1  8  9 24  
:    3  2  7 10 23  
:    4  5  6 11 22  
:   15 14 13 12 21  
:   16 17 18 19 20  
:                  в”ҳ

[fn:1] Almost Perfect Artifacts Improve only in Small Ways: APL is more French than English,
Alan J. Perlis (1978). From [[https://www.jsoftware.com/papers/perlis78.htm][jsoftware]]'s papers collection.
[fn:2] Initially, I intended to rigorously attribute all contributions, but this
quickly filled the text with footnotes. I often get help streamlining my solutions
from [[https://github.com/mlochbaum][Marshall Lochbaum]] (the BQN creator), [[https://github.com/dzaima][dzaima]] (the CBQN developer),
and other fine folks from the BQN matrix [[https://app.element.io/#/room/%23array:matrix.org][room]], thank you all! Please check the [[https://github.com/dzaima/chatlogs][logs]] for more context.
[fn:3] DonвҖҷt believe me? Just ask Kilgore Trout!

#+INCLUDE: "../html-foot.org"
